### ISSUE TITLE
Program type already present: android.support.v4.graphics.drawable.RoundedBitmapDrawable

### ISSUE THREAD

**Issue by neiljaywarner** [MSF-Jarvis/AppRate#2]
Doesn't seem to work with Android 3.1.1 out of box file new project, gives
Program type already present: android.support.v4.graphics.drawable.RoundedBitmapDrawable
with  only 

```kotlin
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        // AppRate(this).init()

    }
}
```

**Comment by MSF-Jarvis** [comment]
Thanks for letting me know, I'll push a new update tonight or tomorrow with this fixed.

**Comment by MSF-Jarvis** [comment]
Can you please try again with [V1.3](https://github.com/MSF-Jarvis/AppRate/releases/tag/1.3)?

**Comment by neiljaywarner** [comment]
@MSF-Jarvis That's awesome you were able to respond, act and publish so quickly, thanks!

however. now it's giving
-
Program type already present: android.support.v13.view.DragAndDropPermissionsCompat
Message{kind=ERROR, text=Program type already present: android.support.v13.view.DragAndDropPermissionsCompat, sources=[Unknown source file], tool name=Optional.of(D8)}
-

**Comment by MSF-Jarvis** [comment]
What gradle plugin is your project using? The 1.3 release works perfectly fine for me.

**Comment by neiljaywarner** [comment]
I will try to check soon but My install is brand new Android studio in the
last few days

**Comment by neiljaywarner** [comment]
Why are you closing please?
Still doesn't work..

**Comment by MSF-Jarvis** [comment]
Eugh why'd this get closed, I don't even remember doing it

**Comment by neiljaywarner** [comment]
Thank you

**Comment by MSF-Jarvis** [comment]
Can you copy your project's build.gradle here? I'm pretty sure this is actually being caused by a dependencies derp on your end

**Comment by janki-vaidya** [comment]
not working yet
